---
title: “Catch”不能出现在“Try”语句之外
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: c8e2b8f9ea5bf5165a97c5b38261a79df1e3b894
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 06/04/2020
ms.locfileid: "84403753"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>“Catch”不能出现在“Try”语句之外
`Catch` 必须出现在 `Try...Catch...Finally` 语句块之内。 或是 `Catch` 块中具有不必要的 `Try` ，或是 `Catch` 语句出现在其对应 `Try` 块的边界之外。  
  
 **错误 ID：** BC30380  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
1. 如果 `Catch` 语句不必要，请删除它，或者请将其置于 `Try...Catch...Finally` 语句块之内。  
  
## <a name="see-also"></a>另请参阅

- [Try...Catch...Finally 语句](../language-reference/statements/try-catch-finally-statement.md)
