---
title: “Throw”语句在“Catch”语句外或“Finally”语句内不能省略操作数
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: c4ab115b01e78c245cbd9f564b50573d6e30c5e7
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 06/04/2020
ms.locfileid: "84414928"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a>“Throw”语句在“Catch”语句外或“Finally”语句内不能省略操作数
`Throw` 语句外的 `Catch` 语句必须提供异常对象的名称。  
  
 **错误 ID：** BC30666  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
1. 指定派生自 `System.Exception`的异常对象的名称。  
  
2. 重构代码，以便 `Throw` 语句位于 `Catch` 块中。  
  
## <a name="see-also"></a>另请参阅

- [Throw 语句](../language-reference/statements/throw-statement.md)
- [Try...Catch...Finally 语句](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [在 .NET 中处理和引发异常](../../standard/exceptions/index.md)
