---
title: 永远不会到达 "Catch" 块，因为 " <name1> " 继承自 " <name2> "
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 560beddd1e9051c43d610fe893a55baa2a5c559a
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 06/04/2020
ms.locfileid: "84395644"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>永远不会到达 "Catch" 块，因为 " \<name1> " 继承自 " \<name2> "
从未到达代码中的 `Catch` 块。  
  
 默认情况下，此消息是一个警告。 有关隐藏警告或将警告视为错误的详细信息，请参见 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)。  
  
 **错误 ID：** BC42029  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
- 删除无关的 `Catch` 块。  
  
## <a name="see-also"></a>另请参阅

- [如何使用 try/catch 块捕获异常](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Try...Catch...Finally 语句](../language-reference/statements/try-catch-finally-statement.md)
